from .models import CarMake, CarModel


def initiate():
    car_make_data = [
        {
            "name": "NISSAN",
            "description": "Great cars. Japanese technology",
            "country_of_origin": "Japan",
            "established_year": 1933,
            "logo": None,  # Update with a valid path if logos are available
        },
        {
            "name": "Mercedes",
            "description": "Great cars. German technology",
            "country_of_origin": "Germany",
            "established_year": 1926,
            "logo": None,
        },
        {
            "name": "Audi",
            "description": "Great cars. German technology",
            "country_of_origin": "Germany",
            "established_year": 1909,
            "logo": None,
        },
        {
            "name": "Kia",
            "description": "Great cars. Korean technology",
            "country_of_origin": "South Korea",
            "established_year": 1944,
            "logo": None,
        },
        {
            "name": "Toyota",
            "description": "Great cars. Japanese technology",
            "country_of_origin": "Japan",
            "established_year": 1937,
            "logo": None,
        },
    ]

    car_make_instances = []
    for data in car_make_data:
        car_make_instances.append(
            CarMake.objects.create(
                name=data["name"],
                description=data["description"],
                country_of_origin=data["country_of_origin"],
                established_year=data["established_year"],
                logo=data["logo"],
            )
        )

    # Create CarModel instances with the corresponding CarMake instances
    car_model_data = [
        {
            "name": "Pathfinder",
            "type": "SUV",
            "year": 2023,
            "car_make": car_make_instances[0],
            "engine_type": "PETROL",
            "seating_capacity": 7,
            "price": 35000.99,
            "color_options": "Red, Blue, Black",
            "fuel_efficiency": 15.5,
        },
        {
            "name": "Qashqai",
            "type": "SUV",
            "year": 2023,
            "car_make": car_make_instances[0],
            "engine_type": "HYBRID",
            "seating_capacity": 5,
            "price": 30000.75,
            "color_options": "Silver, White, Gray",
            "fuel_efficiency": 18.2,
        },
        {
            "name": "XTRAIL",
            "type": "SUV",
            "year": 2023,
            "car_make": car_make_instances[0],
            "engine_type": "DIESEL",
            "seating_capacity": 7,
            "price": 40000.50,
            "color_options": "Black, Red, Green",
            "fuel_efficiency": 14.0,
        },
        {
            "name": "A-Class",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[1],
            "engine_type": "PETROL",
            "seating_capacity": 5,
            "price": 45000.00,
            "color_options": "White, Blue",
            "fuel_efficiency": 16.0,
        },
        {
            "name": "C-Class",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[1],
            "engine_type": "DIESEL",
            "seating_capacity": 5,
            "price": 52000.00,
            "color_options": "Black, Gray, Silver",
            "fuel_efficiency": 12.5,
        },
        {
            "name": "E-Class",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[1],
            "engine_type": "HYBRID",
            "seating_capacity": 5,
            "price": 60000.00,
            "color_options": "White, Blue, Red",
            "fuel_efficiency": 18.0,
        },
        {
            "name": "A4",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[2],
            "engine_type": "PETROL",
            "seating_capacity": 5,
            "price": 38000.00,
            "color_options": "Black, White, Gray",
            "fuel_efficiency": 15.0,
        },
        {
            "name": "A5",
            "type": "Coupe",
            "year": 2023,
            "car_make": car_make_instances[2],
            "engine_type": "DIESEL",
            "seating_capacity": 4,
            "price": 47000.00,
            "color_options": "Blue, Silver, Green",
            "fuel_efficiency": 14.5,
        },
        {
            "name": "A6",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[2],
            "engine_type": "HYBRID",
            "seating_capacity": 5,
            "price": 55000.00,
            "color_options": "Red, Black, Gray",
            "fuel_efficiency": 17.0,
        },
        {
            "name": "Sorrento",
            "type": "SUV",
            "year": 2023,
            "car_make": car_make_instances[3],
            "engine_type": "PETROL",
            "seating_capacity": 7,
            "price": 33000.00,
            "color_options": "White, Blue, Black",
            "fuel_efficiency": 13.0,
        },
        {
            "name": "Carnival",
            "type": "MPV",
            "year": 2023,
            "car_make": car_make_instances[3],
            "engine_type": "HYBRID",
            "seating_capacity": 8,
            "price": 45000.00,
            "color_options": "Silver, Black, Red",
            "fuel_efficiency": 16.0,
        },
        {
            "name": "Cerato",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[3],
            "engine_type": "DIESEL",
            "seating_capacity": 5,
            "price": 25000.00,
            "color_options": "Gray, White, Blue",
            "fuel_efficiency": 18.5,
        },
        {
            "name": "Corolla",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[4],
            "engine_type": "PETROL",
            "seating_capacity": 5,
            "price": 27000.00,
            "color_options": "Silver, Blue, Black",
            "fuel_efficiency": 20.0,
        },
        {
            "name": "Camry",
            "type": "Sedan",
            "year": 2023,
            "car_make": car_make_instances[4],
            "engine_type": "HYBRID",
            "seating_capacity": 5,
            "price": 32000.00,
            "color_options": "White, Red, Black",
            "fuel_efficiency": 22.0,
        },
        {
            "name": "Kluger",
            "type": "SUV",
            "year": 2023,
            "car_make": car_make_instances[4],
            "engine_type": "DIESEL",
            "seating_capacity": 7,
            "price": 45000.00,
            "color_options": "Green, Black, Blue",
            "fuel_efficiency": 14.5,
        },
    ]

    for data in car_model_data:
        CarModel.objects.create(
            name=data["name"],
            car_make=data["car_make"],
            type=data["type"],
            year=data["year"],
            engine_type=data["engine_type"],
            seating_capacity=data["seating_capacity"],
            price=data["price"],
            color_options=data["color_options"],
            fuel_efficiency=data["fuel_efficiency"],
        )
